# Generated by Django 2.0 on 2017-12-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pallier', models.CharField(choices=[('CPY', 'CPY'), ('CP0', 'CP0'), ('P4', 'P4'), ("P'4", "P'4"), ('H4', 'H4'), ('N4', 'N4')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('cnpe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseaux_nationaux.CNPE')),
            ],
        ),
        migrations.CreateModel(
            name='Reseau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('ROB', 'Robinetterie'), ('RCP', 'Recipients'), ('TUY', 'Tuyauteries'), ('AUTO', 'Automatisme'), ('ELEC', 'Elec'), ('MTOUR', 'Machines tournantes')], max_length=200)),
            ],
        ),
    ]
