# Generated by Django 2.0 on 2017-12-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reseaux_nationaux', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnpe',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='cnpe',
            old_name='pallier',
            new_name='palier',
        ),
    ]
