# Generated by Django 2.0 on 2017-12-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseaux_nationaux', '0002_auto_20171210_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='reseaux',
            field=models.ManyToManyField(to='reseaux_nationaux.Reseau'),
        ),
    ]
