# Generated by Django 2.0 on 2018-02-11 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reseaux_nationaux', '0003_personne_reseaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='prenom',
        ),
        migrations.AddField(
            model_name='personne',
            name='metier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reseaux_nationaux.Metier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personne',
            name='cnpe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reseaux_nationaux.CNPE'),
        ),
    ]
